language: node_js
node_js:
  - 10
  - node

script:
  - npm test

jobs:
  include:
    - stage: npm test
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
